// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * GetMCPPort 获取 MCP 服务端口（Wails 绑定方法）
 * @returns {$CancellablePromise<number>}
 */
export function GetMCPPort() {
    return $Call.ByID(435714498);
}

/**
 * IsMCPRunning 查询 MCP 服务状态（Wails 绑定方法）
 * @returns {$CancellablePromise<boolean>}
 */
export function IsMCPRunning() {
    return $Call.ByID(4180574574);
}

/**
 * StartMCP 启动 MCP 服务（Wails 绑定方法）
 * @param {number} port
 * @returns {$CancellablePromise<void>}
 */
export function StartMCP(port) {
    return $Call.ByID(1047098401, port);
}

/**
 * StopMCP 停止 MCP 服务（Wails 绑定方法）
 * @returns {$CancellablePromise<void>}
 */
export function StopMCP() {
    return $Call.ByID(626245887);
}
