// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * @param {string} data
 * @returns {$CancellablePromise<void>}
 */
export function AutoSave(data) {
    return $Call.ByID(769515690, data);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function ClearAutoSave() {
    return $Call.ByID(2590862691);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function ClearCurrentPath() {
    return $Call.ByID(1143040697);
}

/**
 * @param {string} name
 * @param {string} data
 * @returns {$CancellablePromise<string>}
 */
export function CreateProject(name, data) {
    return $Call.ByID(3794430337, name, data);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetAutoSave() {
    return $Call.ByID(2478669646);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetCurrentPath() {
    return $Call.ByID(1213962026);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetRecentProjects() {
    return $Call.ByID(2825977085);
}

/**
 * @param {string} path
 * @returns {$CancellablePromise<string>}
 */
export function ReadFile(path) {
    return $Call.ByID(1365949130, path);
}

/**
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function SetCurrentPath(path) {
    return $Call.ByID(3744920046, path);
}

/**
 * @param {string} path
 * @param {string} data
 * @returns {$CancellablePromise<void>}
 */
export function WriteFile(path, data) {
    return $Call.ByID(1511688169, path, data);
}
