// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * @param {string} data
 * @returns {$CancellablePromise<void>}
 */
export function AutoSave(data) {
    return $Call.ByID(769515690, data);
}

/**
 * @param {string} path
 * @param {string} cardIdsJson
 * @returns {$CancellablePromise<void>}
 */
export function CleanupCardScreenshots(path, cardIdsJson) {
    return $Call.ByID(1268381831, path, cardIdsJson);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function ClearAutoSave() {
    return $Call.ByID(2590862691);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function ClearCurrentPath() {
    return $Call.ByID(1143040697);
}

/**
 * @param {string} name
 * @param {string} projectJson
 * @param {string} sessionsJson
 * @param {string} cardsJson
 * @returns {$CancellablePromise<string>}
 */
export function CreateProject(name, projectJson, sessionsJson, cardsJson) {
    return $Call.ByID(3794430337, name, projectJson, sessionsJson, cardsJson);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetAutoSave() {
    return $Call.ByID(2478669646);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetCurrentPath() {
    return $Call.ByID(1213962026);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetRecentProjects() {
    return $Call.ByID(2825977085);
}

/**
 * @param {string} path
 * @param {string} cardIdsJson
 * @returns {$CancellablePromise<string>}
 */
export function LoadCardScreenshots(path, cardIdsJson) {
    return $Call.ByID(3246821495, path, cardIdsJson);
}

/**
 * @param {string} path
 * @returns {$CancellablePromise<string>}
 */
export function ReadProject(path) {
    return $Call.ByID(2001088337, path);
}

/**
 * @param {string} path
 * @param {string} screenshotsJson
 * @returns {$CancellablePromise<void>}
 */
export function SaveCardScreenshots(path, screenshotsJson) {
    return $Call.ByID(3610063744, path, screenshotsJson);
}

/**
 * @param {string} path
 * @param {string} content
 * @returns {$CancellablePromise<void>}
 */
export function SaveExportFile(path, content) {
    return $Call.ByID(1096197965, path, content);
}

/**
 * @param {string} path
 * @param {string} base64Content
 * @returns {$CancellablePromise<void>}
 */
export function SaveExportFileBinary(path, base64Content) {
    return $Call.ByID(2713292276, path, base64Content);
}

/**
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function SetCurrentPath(path) {
    return $Call.ByID(3744920046, path);
}

/**
 * @param {string} path
 * @param {string} name
 * @param {string} pageType
 * @param {string} designSpecId
 * @param {string} colorScheme
 * @returns {$CancellablePromise<void>}
 */
export function UpdateProjectMeta(path, name, pageType, designSpecId, colorScheme) {
    return $Call.ByID(3987179855, path, name, pageType, designSpecId, colorScheme);
}

/**
 * @param {string} path
 * @param {string} projectJson
 * @param {string} sessionsJson
 * @param {string} cardsJson
 * @returns {$CancellablePromise<void>}
 */
export function WriteProjectFiles(path, projectJson, sessionsJson, cardsJson) {
    return $Call.ByID(59897619, path, projectJson, sessionsJson, cardsJson);
}
